export const SET_SBS_ACTIVE = "SET_SBS_ACTIVE";
export const SET_PLAY_ON_FOCUS_LOST = "SET_PLAY_ON_FOCUS_LOST";
export const SET_TUMBLR_DIALOG_OPEN = "SET_TUMBLR_DIALOG_OPEN";
export const SET_TIMING_DIALOG_OPEN = "SET_TIMING_DIALOG_OPEN";
export const SET_TEXT_DIALOG_OPEN = "SET_TEXT_DIALOG_OPEN";
export const SET_HELP_DIALOG_OPEN = "SET_HELP_DIALOG_OPEN";
export const SET_CONTENT_LOADING = "SET_CONTENT_LOADING";
export const SET_CONTENT_PLAYING = "SET_CONTENT_PLAYING";
export const SET_TUMBLR_LIST = "SET_TUMBLR_LIST";
export const ADD_TUMBLR = "ADD_TUMBLR";
export const REMOVE_TUMBLR = "REMOVE_TUMBLR";
export const ADD_TUMBLR_LINK = "ADD_TUMBLR_LINK";
export const ADD_TUMBLR_IMG = "ADD_TUMBLR_IMG";
export const MODIFY_TIMING_SPEED = "MODIFY_TIMING_SPEED";
export const DESYNC_SBS = "DESYNC_SBS";
export const COVER_IMAGE = "COVER_IMAGE";

export const CLEAR_ALL_DATA = "CLEAR_ALL_DATA";